### ISSUE TITLE
Clear All Bills

### ISSUE THREAD

**Issue by GMA5566** [cs130-w21/dots-ios#11]
## User Story
As a user, I would like the app to have a button that can remove all bill entries from the home view.

## Detailed Description
Give user the ability to remove all bills or all paid bills.

**duplicated with #74**

## Acceptance Criteria
- [x] Given **a remove "Paid" checkbox clicked**, then **toggle remove paid items only boolean**
- [x] Given **clicking on clear all button**, then **remove all bill objects**

## Tasks
- [x] mutating func clearBills() in DotsData class
