### ISSUE TITLE
Initiator/Participants of a Bill

### ISSUE THREAD

**Issue by GMA5566** [cs130-w21/dots-ios#12]
## User Story
As a user, I would like to have the App provide information to let me choose designated bill initiators and participants easily, so that I can assign bills to potentially different portions of people in my group.

## Detailed Description
Upon opening a new bill, the user should be able to choose an initiator, which is the person that paid for the bill. The users should also be able to choose the participants, which are all the people that would be responsible for the bill. The participants and initiator of the bill should be visually clear and distinguishable for the user.

## Acceptance Criteria
- [x] Given **selecting an icon**, then **that participant is selected to be included in the bill**.
- [x] Given **deselecting a selected icon**, then **the participant is removed from the bill**.
- [x] Given **opening a bill**, then **users should be able to clearly tell who is the initiator and who are the participants**.

## Task List
- [x] Icon Selection and Deselection #7 
- [x] Initiator/Participants Visual Differentiation #13 
- [x] mutating func setInitiator() in BillObject class #43 
- [x] mutating func setParticipants() in BillObject class #43 
- [x] mutating func removeParticipant() in BillObject class #43

**Comment by JackZhao98** [comment]
Duplicate. Issue closed.
