### ISSUE TITLE
Item Entry

### ISSUE THREAD

**Issue by lynnozhang7** [cs130-w21/dots-ios#18]
## User Story
As a user, I would like to add item entries to the bill and be able to select the participants and add the price of that item, so that I can record the details of the bill.

## Detailed Description
This is a user interface that allows the user to enter specific items in a bill and assign corresponding participants. The user is expected to be able to type item name, dollar amount, as well as being able to select corresponding participants from the existing participants of the bill. Additionally, the user should be able to save everything he/she typed or selected after clicking a button; similarly, the user should also be able to exit out of this view by clicking another button without saving any changes. 

## Acceptance Criteria
- [x] Given **user inputs of corresponding values and a click on a button**, then **all user inputs will be saved**.
- [x] Given **user clicking on particular participants' icons**, then **only those icons will be saved and mapped to the current entry**.
- [x] Given **user clicking on a button**, then **the user should be able to exit out of the view of entry insertion and go back to the previous view**.

## Task List
- [x] Implement 'EntryObject' class methods (Accessors) #46 
- [x] Implement 'EntryObject' class methods (Mutators) #47

**Comment by GMA5566** [comment]
The third task is partially implemented in that it is currently unclear which view it will go back to. Only the button itself is implemented.
