### ISSUE TITLE
Settle all bills (UI Not Yet Implemented)

### ISSUE THREAD

**Issue by lynnozhang7** [cs130-w21/dots-ios#25]
## User Story
As a user, I would like the app to have a button that will show me the total of who owes who how much, so I can see how each person in the group should pay others back.

## Detailed Description
This function is the core feature of the app, with a single click, the app collects all the bill and bill entry information input from the user, then calculate the amount of money that a person should pay another. The result should be displayed in a clean and simple view.

## Acceptance Criteria
- [x] Given **click on a button**, then **a view pops up with the calculation result**
- [x] Given **swipe or close on the result view**, then **the view dismisses**
- [x] When **some bills are marked as PAID**, the app should **no longer calculate them**

## Task List
- [x] func settleBills() in DotsData class #39 
- [x] func settleBill() in BillObject class #65
