### ISSUE TITLE
Add / Delete Bills

### ISSUE THREAD

**Issue by JackZhao98** [cs130-w21/dots-ios#29]
## User Story
As a **User**, I would like **to add and delete bills** so that **I can manage all bills for the split calculation**.

## Detailed Description
There needs to be a way for users to add, rearrange, delete the bill objects on the home page. When adding a bill, some view should appear that prompts the user to enter bill information.

## Acceptance Criteria
- [x] ➕Given **Clicking some add button**, then **a new bill view pops up**
- [x] 📄Given **Clicking on the edit button**, then **Bills are rearrangeable**
- [x] 🗑Given **Swipe to delete or some delete button in the bill view**, then **remove the corresponding bill correctly**

## Task List
- [x] Bill Title #16 
- [x] Bill Date #17 
- [x] Implement 'BillObject' class methods (Accessors) #42 
- [x] Implement 'BillObject' class methods (Mutators) #43
