### ISSUE TITLE
"Excelsior Package" (UI detail polishing)

### ISSUE THREAD

**Issue by JackZhao98** [cs130-w21/dots-ios#41]
## Epic Description
As a **USER**, I would like **the app to have smooth transition and UI size/position accommodation** so that **I can have a better user experience**.

## Detailed Description
Deliver the best UI/UX we could ever make.

## Related stories
- [x] Customized entry list view, with proper gesture control. #48 
- [x] Keyboard avoidance
- [x] Smooth and flawless transition #54 
- [x] Adaptive UI layout across devices. #56
