### ISSUE TITLE
Implement `BillObject` class methods (Mutators)

### ISSUE THREAD

**Issue by JackZhao98** [cs130-w21/dots-ios#43]
Implement mutator methods inside [Models/BillObject.swift](https://github.com/cs130-w21/8/tree/master/Dots/Dots/Models/BillObject.swift)

### TODO
- [x] mutating func clearEntries()
- [x] mutating func setTitle(newTitle: String)
- [x] mutating func setDate(date: Date)
- [x] mutating func setTaxRate(tax: Double)
- [x] mutating func setInitiator(initiator: Int)
- [x] mutating func setParticipants(participants: [Int])
- [x] mutating func removeParticipant(at: Int)
- [x] mutating func addNewEntry(entry: EntryObject)
- [x] mutating func addNewEntry(entryTitle: String, participants: [Int], value: Double, amount: Int, withTax: Bool)
- [x] mutating func removeEntry(at: Int)

**Comment by JackZhao98** [comment]
6d616b26569c719f423187a8421ff73471306675
