### ISSUE TITLE
Implement `DotsData` class methods (Accessors)

### ISSUE THREAD

**Issue by JackZhao98** [cs130-w21/dots-ios#44]
Implement accessors in [Models/DotsData](https://github.com/cs130-w21/8/tree/master/Dots/Dots/Models/DotsData.swift)

### TODO
- [x] func getGroup() -> [Int] 
- [x] func getPaidBills() -> [BillObject]
- [x] func getUnpaidBills() -> [BillObject]
- [x] func filterBills(associatedWith: Int) -> [BillObject]
