### ISSUE TITLE
Implement `DotsData` class methods (Mutators)

### ISSUE THREAD

**Issue by JackZhao98** [cs130-w21/dots-ios#45]
Implement mutators in [Models/DotsData](https://github.com/cs130-w21/8/tree/master/Dots/Dots/Models/DotsData.swift)

### TODO
- [x] mutating func addToGroup(i: Int /* 0-9 */)
- [x] mutating func removeFromGroup(i: Int /* 0-9 */)
- [x] mutating func clearBills()
- [x] mutating func addNewBill(bill: BillObject)
- [x] mutating func removeBillById(id: UUID)
