### ISSUE TITLE
Implement `EntryObject` class methods (Mutators)

### ISSUE THREAD

**Issue by JackZhao98** [cs130-w21/dots-ios#47]
Implement mutator methods inside [Models/EntryObject.swift](https://github.com/cs130-w21/8/tree/master/Dots/Dots/Models/EntryObject.swift)

### TODO
- [x] mutating func setEntryTitle(title: String) 
- [x] mutating func setEntryValue(value: Double)
- [x] mutating func setEntryAmount(amount: Int)
- [x] mutating func addToParticipants(add: Int)
- [x] mutating func removeFromParticipants(remove: Int)
