### ISSUE TITLE
Clear all paid bills

### ISSUE THREAD

**Issue by GMA5566** [cs130-w21/dots-ios#74]
## User Story
As a user, I would like to remove all the bills that are already paid off, so that I can focus on the ones not yet paid/finished.

## Detailed Description
Implement a button where user can remove all paid bills with one click

## Acceptance Criteria
- [x] Given **click on clear button**, then **pop up a window to prompt user whether to remove all paid bills**
- [x] Given **click on yes**, then **remove all paid bills**
- [x] Given **click on no**, then **dismiss window**

## Tasks
- [x] Added mutating func clearPaidBill()  in DotsData class
