### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by lynnozhang7** [cs130-w21/dots-ios#80]
## Epic
Description and User Benefit:
Additional features are provided to users to filter their bills and perform some action to parts or all of their bills. These features include: group by initiator, mark all bills as paid, hide/unhide paid bills, clear all paid bills, and enable face ID. The first four features give user more flexibility with how to display and handle their bills. The last feature gives user more security in accessing the application.

## User Stories
- [x] A contextual menu with utility buttons and settings #85 
- [x] Group by initiator #71 
- [x] Mark all bills as paid #72 
- [x] Hide/unhide paid bills #73 
- [x] Clear all paid bills #74 
- [x] Enable face ID #75
