### ISSUE TITLE
Bill Collection Visualization

### ISSUE THREAD

**Issue by GMA5566** [cs130-w21/dots-ios#9]
## User Story
As a user, I would like to have the app display the most recently added bill at a conspicuous place, so that I can easily confirm my addition of the bill without having to look at other older bills.

## Detailed Description
Create a bill view that displays **Bill Title**, **Bill Amount**, **Bill Date**, and also indicates the **Initiator** and **Participants** using corresponding colors. The view should also offers an option to **edit** and **delete**. 
## Acceptance Criteria
- [x] Given **bill date and bill title**, then **the bill should display the tile and date properly**
- [x] Given **proper data input**, then **the bill displays as a list on the home screen**
## Task List
- [x] Refer to **Card View** #10
